# Configuration for development teams
language: "en-US"

reviews:
  profile: "assertive"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["master", "main", "development", "release/*"]
    ignore_title_keywords:
      - "wip"
      - "draft"
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    title:
      mode: "warning"
      requirements: "Title should be concise and descriptive. Title should start with feature/Add new dockerfile or bugfix/Fix bug on shops module."
    custom_checks: ["Any pull request to main or master branch must include title such as [RELEASE] - DDMMYYYY - API NAME "]
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true
    dotenvLint:
      enabled: true
    yamllint:
      enabled: true

chat:
  art: true
  auto_reply: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/.cursorrules"
      - "**/CODING_STANDARDS.md"