# Configuration for development teams
language: "en-US"

reviews:
  profile: "assertive"
  high_level_summary: true
  poem: false
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["master", "main", "development", "release/.*"]
    ignore_title_keywords:
      - "wip"
      - "draft"
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    title:
      mode: "warning"
      requirements: "Title should be concise and descriptive. Prefer a prefix with JIRA ticket follow up with the branch typ and a title '[TICKET01]-[FEATURE] - SUMMARY' for feature branch, '[TICKET02]-[HOTFIX] - SUMMARY' for hot or bug fix branch.
    description:
      mode: "warning"
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true
    dotenvLint:
      enabled: true
    yamllint:
      enabled: true
chat:
  art: true
  auto_reply: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CODE_GUIDELINES.md"