services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: development
      ROUTE_PREPEND: jiran-tetangga
      HOSTNAME: apidev
      API_VERSION: ${API_VERSION}
      APP_VERSION: ${APP_VERSION}
      VERSION: ${VERSION}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PORT: ${PORT}
      INFISICAL_URI: http://infisical-backend:8080
      INFISICAL_PROJECT_ID: 'Inifisical project ID'
      INFISICAL_CLIENT_ID: 'Inifisical client ID'
      INFISICAL_CLIENT_SECRET: 'Inifisical client secret'
      INFISICAL_ENV: dev
    command: ["npm", "start"]
    ports:
      - "3500:3500"
    networks:
      - jiran-tetangga-networks
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/ssrc/app/node_modules
    command: ["npm", "start"]
    
  mongodb:
    image: mongo:noble
    container_name: mongodb
    restart: always
    volumes:
      - db_data:/data/db
    ports:
      - "27019:27017"
    networks:
      - jiran-tetangga-networks
    healthcheck:
      test: ["CMD", "mongosh" ,"--eval", "db.adminCommand({ping: 1})", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    container_name: nginx
    image: nginx:stable-perl
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - jiran-tetangga-networks

networks:
  jiran-tetangga-networks:
    external: true
    name: jiran-tetangga-networks

volumes:
  db_data: