# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For exampleshttps://github.com/da-imran/jiran-tetangga/security, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: development
      ROUTE_PREPEND: jiran-tetangga
      HOSTNAME: apidev
      API_VERSION: ${API_VERSION}
      APP_VERSION: ${APP_VERSION}
      VERSION: ${VERSION}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PORT: ${PORT}
      INFISICAL_URI: http://infisical-backend:8080
      INFISICAL_PROJECT_ID: '6010d8b2-a186-422f-b0ba-d977e3a8d1a3'
      INFISICAL_CLIENT_ID: 'dfd4658e-8ccb-4814-94ba-d548fa52dfc8'
      INFISICAL_CLIENT_SECRET: 'ed38e448d86fa6fe0d8ae83a744712fb37261974b77eb1eb0c3cec12c3df9f56'
      INFISICAL_ENV: dev
    command: ["npm", "start"]
    ports:
      - "3500:3500"
    networks:
      - jiran-tetangga-networks
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
    
  mongodb:
    image: mongo:noble
    container_name: mongodb
    restart: always
    volumes:
      - db_data:/data/db
    ports:
      - "27019:27017"
    networks:
      - jiran-tetangga-networks
    healthcheck:
      test: ["CMD", "mongosh" ,"--eval", "db.adminCommand({ping: 1})", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    container_name: nginx
    image: nginx:stable-perl
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - jiran-tetangga-networks

networks:
  jiran-tetangga-networks:
    external: true
    name: jiran-tetangga-networks

volumes:
  db_data: