name: Deploy to AWS EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SHH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC@_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd jiran-tetangga
            git pull origin master
            docker-compose up --build -d
            exit
          EOF